#!/usr/bin/env php
<?php
// Copyright 2021 The dotcoo <dotcoo@163.com>. All rights reserved.

declare(strict_types=1);

require_once __DIR__ . '/vendor/phpm/framework/src/Server.php';

if (PHP_SAPI != 'cli') { exit('not cli!'); }

$serv = \net\phpm\framework\Server::getInstance();
$serv->start();
